/**
 * Discovery Harness — `npm run list-tools`
 *
 * Instantiates every tool register function against a recording stub
 * that captures tool name, title, and description. Emits a markdown
 * index grouped by domain for use in README generation.
 *
 * Usage:
 *   npm run list-tools           # prints markdown to stdout
 *   npm run list-tools -- --json # prints JSON to stdout
 */

// ── Recording stub ─────────────────────────────────────────────────────
interface RecordedTool {
  name: string;
  title?: string;
  description?: string;
  inputSchema?: unknown;
  annotations?: Record<string, unknown>;
  domain: string;
}

const captured: RecordedTool[] = [];
let currentDomain = "unknown";

interface ToolRegistration {
  title?: string;
  description?: string;
  inputSchema?: unknown;
  annotations?: Record<string, unknown>;
}

class RecordingServer {
  registerTool(
    name: string,
    options: ToolRegistration,
    _handler: (...args: unknown[]) => unknown
  ): void {
    captured.push({
      name,
      title: options.title,
      description: options.description,
      inputSchema: options.inputSchema,
      annotations: options.annotations,
      domain: currentDomain,
    });
  }
}

type RegisterFn = (server: unknown) => void;

async function runDiscovery(): Promise<RecordedTool[]> {
  const modules: Array<{ domain: string; importFn: () => Promise<Record<string, unknown>> }> = [
    { domain: "luau-execution", importFn: () => import("../tools/luau-execution.js") },
    { domain: "data-stores", importFn: () => import("../tools/data-stores.js") },
    { domain: "ordered-data-stores", importFn: () => import("../tools/ordered-data-stores.js") },
    { domain: "memory-stores", importFn: () => import("../tools/memory-stores.js") },
    { domain: "messaging", importFn: () => import("../tools/messaging.js") },
    { domain: "universes", importFn: () => import("../tools/universes.js") },
    { domain: "monetization", importFn: () => import("../tools/monetization.js") },
    { domain: "creator-store", importFn: () => import("../tools/creator-store.js") },
    { domain: "config", importFn: () => import("../tools/config.js") },
    { domain: "secrets", importFn: () => import("../tools/secrets.js") },
    { domain: "user-restrictions", importFn: () => import("../tools/user-restrictions.js") },
    { domain: "assets", importFn: () => import("../tools/assets.js") },
    { domain: "groups", importFn: () => import("../tools/groups.js") },
    { domain: "users", importFn: () => import("../tools/users.js") },
    { domain: "badges", importFn: () => import("../tools/badges.js") },
    { domain: "thumbnails", importFn: () => import("../tools/thumbnails.js") },
    { domain: "notifications", importFn: () => import("../tools/notifications.js") },
    { domain: "generative-ai", importFn: () => import("../tools/generative-ai.js") },
  ];

  const server = new RecordingServer();

  for (const { domain, importFn } of modules) {
    currentDomain = domain;
    const mod = await importFn();
    // Each module exports a single `registerXxxTools` function.
    const registerFn = Object.values(mod).find(
      (v): v is RegisterFn => typeof v === "function" && v.name.startsWith("register")
    );
    if (!registerFn) {
      process.stderr.write(`⚠️  No register function found in ${domain}\n`);
      continue;
    }
    registerFn(server);
  }

  return captured;
}

function formatMarkdown(tools: RecordedTool[]): string {
  const byDomain = new Map<string, RecordedTool[]>();
  for (const t of tools) {
    if (!byDomain.has(t.domain)) byDomain.set(t.domain, []);
    byDomain.get(t.domain)!.push(t);
  }

  const lines: string[] = [];
  lines.push(`# Tool Index`);
  lines.push("");
  lines.push(`_Auto-generated by \`scripts/list-tools.ts\`. **Total tools: ${tools.length}**._`);
  lines.push("");

  const sortedDomains = [...byDomain.keys()].sort();
  for (const domain of sortedDomains) {
    const tools = byDomain.get(domain)!;
    lines.push(`## ${domain} (${tools.length})`);
    lines.push("");
    for (const t of tools) {
      const firstLine = (t.description || "").split("\n")[0].trim();
      lines.push(`- **\`${t.name}\`** — ${t.title || ""}`);
      if (firstLine) lines.push(`  _${firstLine}_`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function formatJson(tools: RecordedTool[]): string {
  return JSON.stringify(
    {
      total: tools.length,
      domains: tools.reduce<Record<string, number>>((acc, t) => {
        acc[t.domain] = (acc[t.domain] || 0) + 1;
        return acc;
      }, {}),
      tools: tools.map((t) => ({
        name: t.name,
        title: t.title,
        domain: t.domain,
      })),
    },
    null,
    2
  );
}

async function main(): Promise<void> {
  const json = process.argv.includes("--json");
  try {
    const tools = await runDiscovery();
    process.stdout.write(json ? formatJson(tools) : formatMarkdown(tools));
    process.stdout.write("\n");
    process.stderr.write(`\n✅ Discovered ${tools.length} tools across ${new Set(tools.map((t) => t.domain)).size} domains\n`);
  } catch (err) {
    process.stderr.write(`❌ Discovery failed: ${err instanceof Error ? err.message : String(err)}\n`);
    process.exit(1);
  }
}

void main();
